// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: grpc_mesh.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_RegisterPeer_FullMethodName  = "/grpc_mesh.rpc.v1.ControlPlane/RegisterPeer"
	ControlPlane_Heartbeat_FullMethodName     = "/grpc_mesh.rpc.v1.ControlPlane/Heartbeat"
	ControlPlane_UpdateMethods_FullMethodName = "/grpc_mesh.rpc.v1.ControlPlane/UpdateMethods"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlPlane handles peer lifecycle.
type ControlPlaneClient interface {
	RegisterPeer(ctx context.Context, in *PeerMetadata, opts ...grpc.CallOption) (*RegisterAck, error)
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error)
	UpdateMethods(ctx context.Context, in *UpdateMethodsRequest, opts ...grpc.CallOption) (*UpdateMethodsResponse, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) RegisterPeer(ctx context.Context, in *PeerMetadata, opts ...grpc.CallOption) (*RegisterAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAck)
	err := c.cc.Invoke(ctx, ControlPlane_RegisterPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[0], ControlPlane_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatRequest, HeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_HeartbeatClient = grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse]

func (c *controlPlaneClient) UpdateMethods(ctx context.Context, in *UpdateMethodsRequest, opts ...grpc.CallOption) (*UpdateMethodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMethodsResponse)
	err := c.cc.Invoke(ctx, ControlPlane_UpdateMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
//
// ControlPlane handles peer lifecycle.
type ControlPlaneServer interface {
	RegisterPeer(context.Context, *PeerMetadata) (*RegisterAck, error)
	Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error
	UpdateMethods(context.Context, *UpdateMethodsRequest) (*UpdateMethodsResponse, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) RegisterPeer(context.Context, *PeerMetadata) (*RegisterAck, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterPeer not implemented")
}
func (UnimplementedControlPlaneServer) Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControlPlaneServer) UpdateMethods(context.Context, *UpdateMethodsRequest) (*UpdateMethodsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMethods not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_RegisterPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerMetadata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RegisterPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RegisterPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RegisterPeer(ctx, req.(*PeerMetadata))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServer).Heartbeat(&grpc.GenericServerStream[HeartbeatRequest, HeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_HeartbeatServer = grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]

func _ControlPlane_UpdateMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).UpdateMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_UpdateMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).UpdateMethods(ctx, req.(*UpdateMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_mesh.rpc.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterPeer",
			Handler:    _ControlPlane_RegisterPeer_Handler,
		},
		{
			MethodName: "UpdateMethods",
			Handler:    _ControlPlane_UpdateMethods_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _ControlPlane_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc_mesh.proto",
}

const (
	InvokePlane_Invoke_FullMethodName       = "/grpc_mesh.rpc.v1.InvokePlane/Invoke"
	InvokePlane_InvokeStream_FullMethodName = "/grpc_mesh.rpc.v1.InvokePlane/InvokeStream"
)

// InvokePlaneClient is the client API for InvokePlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InvokePlane handles reverse RPC invocations.
type InvokePlaneClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	InvokeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InvokeRequest, InvokeResponse], error)
}

type invokePlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewInvokePlaneClient(cc grpc.ClientConnInterface) InvokePlaneClient {
	return &invokePlaneClient{cc}
}

func (c *invokePlaneClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, InvokePlane_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invokePlaneClient) InvokeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InvokeRequest, InvokeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InvokePlane_ServiceDesc.Streams[0], InvokePlane_InvokeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InvokeRequest, InvokeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InvokePlane_InvokeStreamClient = grpc.BidiStreamingClient[InvokeRequest, InvokeResponse]

// InvokePlaneServer is the server API for InvokePlane service.
// All implementations must embed UnimplementedInvokePlaneServer
// for forward compatibility.
//
// InvokePlane handles reverse RPC invocations.
type InvokePlaneServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	InvokeStream(grpc.BidiStreamingServer[InvokeRequest, InvokeResponse]) error
	mustEmbedUnimplementedInvokePlaneServer()
}

// UnimplementedInvokePlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInvokePlaneServer struct{}

func (UnimplementedInvokePlaneServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedInvokePlaneServer) InvokeStream(grpc.BidiStreamingServer[InvokeRequest, InvokeResponse]) error {
	return status.Error(codes.Unimplemented, "method InvokeStream not implemented")
}
func (UnimplementedInvokePlaneServer) mustEmbedUnimplementedInvokePlaneServer() {}
func (UnimplementedInvokePlaneServer) testEmbeddedByValue()                     {}

// UnsafeInvokePlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvokePlaneServer will
// result in compilation errors.
type UnsafeInvokePlaneServer interface {
	mustEmbedUnimplementedInvokePlaneServer()
}

func RegisterInvokePlaneServer(s grpc.ServiceRegistrar, srv InvokePlaneServer) {
	// If the following call panics, it indicates UnimplementedInvokePlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InvokePlane_ServiceDesc, srv)
}

func _InvokePlane_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvokePlaneServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvokePlane_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvokePlaneServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvokePlane_InvokeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InvokePlaneServer).InvokeStream(&grpc.GenericServerStream[InvokeRequest, InvokeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InvokePlane_InvokeStreamServer = grpc.BidiStreamingServer[InvokeRequest, InvokeResponse]

// InvokePlane_ServiceDesc is the grpc.ServiceDesc for InvokePlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvokePlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_mesh.rpc.v1.InvokePlane",
	HandlerType: (*InvokePlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _InvokePlane_Invoke_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InvokeStream",
			Handler:       _InvokePlane_InvokeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc_mesh.proto",
}
