// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: grpc_mesh.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PeerMetadata describes static attributes reported at registration time.
type PeerMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMetadata) Reset() {
	*x = PeerMetadata{}
	mi := &file_grpc_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMetadata) ProtoMessage() {}

func (x *PeerMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMetadata.ProtoReflect.Descriptor instead.
func (*PeerMetadata) Descriptor() ([]byte, []int) {
	return file_grpc_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *PeerMetadata) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PeerMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PeerMetadata) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// RegisterPeerRequest wraps the metadata for registration.
type RegisterPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *PeerMetadata          `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPeerRequest) Reset() {
	*x = RegisterPeerRequest{}
	mi := &file_grpc_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPeerRequest) ProtoMessage() {}

func (x *RegisterPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPeerRequest.ProtoReflect.Descriptor instead.
func (*RegisterPeerRequest) Descriptor() ([]byte, []int) {
	return file_grpc_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterPeerRequest) GetMetadata() *PeerMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// RegisterPeerResponse acknowledges peer registration.
type RegisterPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	AssignedId    string                 `protobuf:"bytes,2,opt,name=assigned_id,json=assignedId,proto3" json:"assigned_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPeerResponse) Reset() {
	*x = RegisterPeerResponse{}
	mi := &file_grpc_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPeerResponse) ProtoMessage() {}

func (x *RegisterPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPeerResponse.ProtoReflect.Descriptor instead.
func (*RegisterPeerResponse) Descriptor() ([]byte, []int) {
	return file_grpc_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterPeerResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterPeerResponse) GetAssignedId() string {
	if x != nil {
		return x.AssignedId
	}
	return ""
}

func (x *RegisterPeerResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Heartbeat messages keep sessions alive.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *PeerMetadata          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	TimestampMs   uint64                 `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_grpc_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_grpc_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetMeta() *PeerMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *HeartbeatRequest) GetTimestampMs() uint64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_grpc_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_grpc_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HeartbeatResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// UpdateMethods communicates the callable methods list.
type MethodDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodDescriptor) Reset() {
	*x = MethodDescriptor{}
	mi := &file_grpc_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodDescriptor) ProtoMessage() {}

func (x *MethodDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodDescriptor.ProtoReflect.Descriptor instead.
func (*MethodDescriptor) Descriptor() ([]byte, []int) {
	return file_grpc_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *MethodDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MethodDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MethodDescriptor) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MethodDescriptor) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type UpdateMethodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Methods       []*MethodDescriptor    `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMethodsRequest) Reset() {
	*x = UpdateMethodsRequest{}
	mi := &file_grpc_mesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMethodsRequest) ProtoMessage() {}

func (x *UpdateMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_mesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMethodsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMethodsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_mesh_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMethodsRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *UpdateMethodsRequest) GetMethods() []*MethodDescriptor {
	if x != nil {
		return x.Methods
	}
	return nil
}

type UpdateMethodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMethodsResponse) Reset() {
	*x = UpdateMethodsResponse{}
	mi := &file_grpc_mesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMethodsResponse) ProtoMessage() {}

func (x *UpdateMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_mesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMethodsResponse.ProtoReflect.Descriptor instead.
func (*UpdateMethodsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_mesh_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMethodsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// InvokeRequest asks grpc-mesh-node to execute a method.
type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_grpc_mesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_mesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_grpc_mesh_proto_rawDescGZIP(), []int{8}
}

func (x *InvokeRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *InvokeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *InvokeRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// InvokeResponse returns the execution outcome.
type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Result        []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	CorrelationId string                 `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ElapsedMs     uint64                 `protobuf:"varint,7,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_grpc_mesh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_mesh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_grpc_mesh_proto_rawDescGZIP(), []int{9}
}

func (x *InvokeResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *InvokeResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *InvokeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InvokeResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *InvokeResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *InvokeResponse) GetElapsedMs() uint64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

// InvokeStreamRequest is the request type for the InvokeStream RPC.
type InvokeStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeStreamRequest) Reset() {
	*x = InvokeStreamRequest{}
	mi := &file_grpc_mesh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeStreamRequest) ProtoMessage() {}

func (x *InvokeStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_mesh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeStreamRequest.ProtoReflect.Descriptor instead.
func (*InvokeStreamRequest) Descriptor() ([]byte, []int) {
	return file_grpc_mesh_proto_rawDescGZIP(), []int{10}
}

func (x *InvokeStreamRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *InvokeStreamRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeStreamRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeStreamRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *InvokeStreamRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// InvokeStreamResponse is the response type for the InvokeStream RPC.
type InvokeStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Result        []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	CorrelationId string                 `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ElapsedMs     uint64                 `protobuf:"varint,7,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeStreamResponse) Reset() {
	*x = InvokeStreamResponse{}
	mi := &file_grpc_mesh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeStreamResponse) ProtoMessage() {}

func (x *InvokeStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_mesh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeStreamResponse.ProtoReflect.Descriptor instead.
func (*InvokeStreamResponse) Descriptor() ([]byte, []int) {
	return file_grpc_mesh_proto_rawDescGZIP(), []int{11}
}

func (x *InvokeStreamResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *InvokeStreamResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeStreamResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *InvokeStreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InvokeStreamResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *InvokeStreamResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *InvokeStreamResponse) GetElapsedMs() uint64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []byte                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_grpc_mesh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_mesh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_grpc_mesh_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_grpc_mesh_proto protoreflect.FileDescriptor

const file_grpc_mesh_proto_rawDesc = "" +
	"\n" +
	"\x0fgrpc_mesh.proto\x12\x10grpc_mesh.rpc.v1\"\xe4\x01\n" +
	"\fPeerMetadata\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12N\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2..grpc_mesh.rpc.v1.PeerMetadata.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x13RegisterPeerRequest\x12:\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.grpc_mesh.rpc.v1.PeerMetadataR\bmetadata\"k\n" +
	"\x14RegisterPeerResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1f\n" +
	"\vassigned_id\x18\x02 \x01(\tR\n" +
	"assignedId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"i\n" +
	"\x10HeartbeatRequest\x122\n" +
	"\x04meta\x18\x01 \x01(\v2\x1e.grpc_mesh.rpc.v1.PeerMetadataR\x04meta\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x04R\vtimestampMs\"G\n" +
	"\x11HeartbeatResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xdb\x01\n" +
	"\x10MethodDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12C\n" +
	"\x05extra\x18\x04 \x03(\v2-.grpc_mesh.rpc.v1.MethodDescriptor.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\x14UpdateMethodsRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12<\n" +
	"\amethods\x18\x02 \x03(\v2\".grpc_mesh.rpc.v1.MethodDescriptorR\amethods\"1\n" +
	"\x15UpdateMethodsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa0\x01\n" +
	"\rInvokeRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\rR\ttimeoutMs\"\xee\x01\n" +
	"\x0eInvokeResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x123\n" +
	"\x05error\x18\x05 \x01(\v2\x1d.grpc_mesh.rpc.v1.ErrorDetailR\x05error\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\a \x01(\x04R\telapsedMs\"\xa6\x01\n" +
	"\x13InvokeStreamRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\rR\ttimeoutMs\"\xf4\x01\n" +
	"\x14InvokeStreamResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x123\n" +
	"\x05error\x18\x05 \x01(\v2\x1d.grpc_mesh.rpc.v1.ErrorDetailR\x05error\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\a \x01(\x04R\telapsedMs\"U\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\fR\adetails2\xb0\x02\n" +
	"\x13ControlPlaneService\x12]\n" +
	"\fRegisterPeer\x12%.grpc_mesh.rpc.v1.RegisterPeerRequest\x1a&.grpc_mesh.rpc.v1.RegisterPeerResponse\x12X\n" +
	"\tHeartbeat\x12\".grpc_mesh.rpc.v1.HeartbeatRequest\x1a#.grpc_mesh.rpc.v1.HeartbeatResponse(\x010\x01\x12`\n" +
	"\rUpdateMethods\x12&.grpc_mesh.rpc.v1.UpdateMethodsRequest\x1a'.grpc_mesh.rpc.v1.UpdateMethodsResponse2\xc4\x01\n" +
	"\x12InvokePlaneService\x12K\n" +
	"\x06Invoke\x12\x1f.grpc_mesh.rpc.v1.InvokeRequest\x1a .grpc_mesh.rpc.v1.InvokeResponse\x12a\n" +
	"\fInvokeStream\x12%.grpc_mesh.rpc.v1.InvokeStreamRequest\x1a&.grpc_mesh.rpc.v1.InvokeStreamResponse(\x010\x01B/Z-github.com/grpc-mesh/grpc-mesh-server/pkg/rpcb\x06proto3"

var (
	file_grpc_mesh_proto_rawDescOnce sync.Once
	file_grpc_mesh_proto_rawDescData []byte
)

func file_grpc_mesh_proto_rawDescGZIP() []byte {
	file_grpc_mesh_proto_rawDescOnce.Do(func() {
		file_grpc_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_mesh_proto_rawDesc), len(file_grpc_mesh_proto_rawDesc)))
	})
	return file_grpc_mesh_proto_rawDescData
}

var file_grpc_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_grpc_mesh_proto_goTypes = []any{
	(*PeerMetadata)(nil),          // 0: grpc_mesh.rpc.v1.PeerMetadata
	(*RegisterPeerRequest)(nil),   // 1: grpc_mesh.rpc.v1.RegisterPeerRequest
	(*RegisterPeerResponse)(nil),  // 2: grpc_mesh.rpc.v1.RegisterPeerResponse
	(*HeartbeatRequest)(nil),      // 3: grpc_mesh.rpc.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 4: grpc_mesh.rpc.v1.HeartbeatResponse
	(*MethodDescriptor)(nil),      // 5: grpc_mesh.rpc.v1.MethodDescriptor
	(*UpdateMethodsRequest)(nil),  // 6: grpc_mesh.rpc.v1.UpdateMethodsRequest
	(*UpdateMethodsResponse)(nil), // 7: grpc_mesh.rpc.v1.UpdateMethodsResponse
	(*InvokeRequest)(nil),         // 8: grpc_mesh.rpc.v1.InvokeRequest
	(*InvokeResponse)(nil),        // 9: grpc_mesh.rpc.v1.InvokeResponse
	(*InvokeStreamRequest)(nil),   // 10: grpc_mesh.rpc.v1.InvokeStreamRequest
	(*InvokeStreamResponse)(nil),  // 11: grpc_mesh.rpc.v1.InvokeStreamResponse
	(*ErrorDetail)(nil),           // 12: grpc_mesh.rpc.v1.ErrorDetail
	nil,                           // 13: grpc_mesh.rpc.v1.PeerMetadata.AttributesEntry
	nil,                           // 14: grpc_mesh.rpc.v1.MethodDescriptor.ExtraEntry
}
var file_grpc_mesh_proto_depIdxs = []int32{
	13, // 0: grpc_mesh.rpc.v1.PeerMetadata.attributes:type_name -> grpc_mesh.rpc.v1.PeerMetadata.AttributesEntry
	0,  // 1: grpc_mesh.rpc.v1.RegisterPeerRequest.metadata:type_name -> grpc_mesh.rpc.v1.PeerMetadata
	0,  // 2: grpc_mesh.rpc.v1.HeartbeatRequest.meta:type_name -> grpc_mesh.rpc.v1.PeerMetadata
	14, // 3: grpc_mesh.rpc.v1.MethodDescriptor.extra:type_name -> grpc_mesh.rpc.v1.MethodDescriptor.ExtraEntry
	5,  // 4: grpc_mesh.rpc.v1.UpdateMethodsRequest.methods:type_name -> grpc_mesh.rpc.v1.MethodDescriptor
	12, // 5: grpc_mesh.rpc.v1.InvokeResponse.error:type_name -> grpc_mesh.rpc.v1.ErrorDetail
	12, // 6: grpc_mesh.rpc.v1.InvokeStreamResponse.error:type_name -> grpc_mesh.rpc.v1.ErrorDetail
	1,  // 7: grpc_mesh.rpc.v1.ControlPlaneService.RegisterPeer:input_type -> grpc_mesh.rpc.v1.RegisterPeerRequest
	3,  // 8: grpc_mesh.rpc.v1.ControlPlaneService.Heartbeat:input_type -> grpc_mesh.rpc.v1.HeartbeatRequest
	6,  // 9: grpc_mesh.rpc.v1.ControlPlaneService.UpdateMethods:input_type -> grpc_mesh.rpc.v1.UpdateMethodsRequest
	8,  // 10: grpc_mesh.rpc.v1.InvokePlaneService.Invoke:input_type -> grpc_mesh.rpc.v1.InvokeRequest
	10, // 11: grpc_mesh.rpc.v1.InvokePlaneService.InvokeStream:input_type -> grpc_mesh.rpc.v1.InvokeStreamRequest
	2,  // 12: grpc_mesh.rpc.v1.ControlPlaneService.RegisterPeer:output_type -> grpc_mesh.rpc.v1.RegisterPeerResponse
	4,  // 13: grpc_mesh.rpc.v1.ControlPlaneService.Heartbeat:output_type -> grpc_mesh.rpc.v1.HeartbeatResponse
	7,  // 14: grpc_mesh.rpc.v1.ControlPlaneService.UpdateMethods:output_type -> grpc_mesh.rpc.v1.UpdateMethodsResponse
	9,  // 15: grpc_mesh.rpc.v1.InvokePlaneService.Invoke:output_type -> grpc_mesh.rpc.v1.InvokeResponse
	11, // 16: grpc_mesh.rpc.v1.InvokePlaneService.InvokeStream:output_type -> grpc_mesh.rpc.v1.InvokeStreamResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_grpc_mesh_proto_init() }
func file_grpc_mesh_proto_init() {
	if File_grpc_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_mesh_proto_rawDesc), len(file_grpc_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_grpc_mesh_proto_goTypes,
		DependencyIndexes: file_grpc_mesh_proto_depIdxs,
		MessageInfos:      file_grpc_mesh_proto_msgTypes,
	}.Build()
	File_grpc_mesh_proto = out.File
	file_grpc_mesh_proto_goTypes = nil
	file_grpc_mesh_proto_depIdxs = nil
}
