// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: waemu.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PeerMetadata describes static attributes reported at registration time.
type PeerMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMetadata) Reset() {
	*x = PeerMetadata{}
	mi := &file_waemu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMetadata) ProtoMessage() {}

func (x *PeerMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_waemu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMetadata.ProtoReflect.Descriptor instead.
func (*PeerMetadata) Descriptor() ([]byte, []int) {
	return file_waemu_proto_rawDescGZIP(), []int{0}
}

func (x *PeerMetadata) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PeerMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PeerMetadata) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// RegisterAck acknowledges peer registration.
type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	AssignedId    string                 `protobuf:"bytes,2,opt,name=assigned_id,json=assignedId,proto3" json:"assigned_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_waemu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_waemu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_waemu_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterAck) GetAssignedId() string {
	if x != nil {
		return x.AssignedId
	}
	return ""
}

func (x *RegisterAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Heartbeat messages keep sessions alive.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *PeerMetadata          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	TimestampMs   uint64                 `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_waemu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_waemu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_waemu_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetMeta() *PeerMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *HeartbeatRequest) GetTimestampMs() uint64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_waemu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_waemu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_waemu_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HeartbeatResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// UpdateMethods communicates the callable methods list.
type MethodDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodDescriptor) Reset() {
	*x = MethodDescriptor{}
	mi := &file_waemu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodDescriptor) ProtoMessage() {}

func (x *MethodDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_waemu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodDescriptor.ProtoReflect.Descriptor instead.
func (*MethodDescriptor) Descriptor() ([]byte, []int) {
	return file_waemu_proto_rawDescGZIP(), []int{4}
}

func (x *MethodDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MethodDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MethodDescriptor) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MethodDescriptor) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type UpdateMethodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Methods       []*MethodDescriptor    `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMethodsRequest) Reset() {
	*x = UpdateMethodsRequest{}
	mi := &file_waemu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMethodsRequest) ProtoMessage() {}

func (x *UpdateMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_waemu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMethodsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMethodsRequest) Descriptor() ([]byte, []int) {
	return file_waemu_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMethodsRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *UpdateMethodsRequest) GetMethods() []*MethodDescriptor {
	if x != nil {
		return x.Methods
	}
	return nil
}

type UpdateMethodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMethodsResponse) Reset() {
	*x = UpdateMethodsResponse{}
	mi := &file_waemu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMethodsResponse) ProtoMessage() {}

func (x *UpdateMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_waemu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMethodsResponse.ProtoReflect.Descriptor instead.
func (*UpdateMethodsResponse) Descriptor() ([]byte, []int) {
	return file_waemu_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMethodsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// InvokeRequest asks grpc-mesh-node to execute a method.
type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_waemu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_waemu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_waemu_proto_rawDescGZIP(), []int{7}
}

func (x *InvokeRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *InvokeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *InvokeRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// InvokeResponse returns the execution outcome.
type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Result        []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	CorrelationId string                 `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ElapsedMs     uint64                 `protobuf:"varint,7,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_waemu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_waemu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_waemu_proto_rawDescGZIP(), []int{8}
}

func (x *InvokeResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *InvokeResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *InvokeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InvokeResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *InvokeResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *InvokeResponse) GetElapsedMs() uint64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []byte                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_waemu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_waemu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_waemu_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_waemu_proto protoreflect.FileDescriptor

const file_waemu_proto_rawDesc = "" +
	"\n" +
	"\vwaemu.proto\x12\fwaemu.rpc.v1\"\xe0\x01\n" +
	"\fPeerMetadata\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12J\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2*.waemu.rpc.v1.PeerMetadata.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\vRegisterAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1f\n" +
	"\vassigned_id\x18\x02 \x01(\tR\n" +
	"assignedId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"e\n" +
	"\x10HeartbeatRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x1a.waemu.rpc.v1.PeerMetadataR\x04meta\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x04R\vtimestampMs\"G\n" +
	"\x11HeartbeatResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xd7\x01\n" +
	"\x10MethodDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12?\n" +
	"\x05extra\x18\x04 \x03(\v2).waemu.rpc.v1.MethodDescriptor.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x14UpdateMethodsRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x128\n" +
	"\amethods\x18\x02 \x03(\v2\x1e.waemu.rpc.v1.MethodDescriptorR\amethods\"1\n" +
	"\x15UpdateMethodsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa0\x01\n" +
	"\rInvokeRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\rR\ttimeoutMs\"\xea\x01\n" +
	"\x0eInvokeResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12/\n" +
	"\x05error\x18\x05 \x01(\v2\x19.waemu.rpc.v1.ErrorDetailR\x05error\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\a \x01(\x04R\telapsedMs\"U\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\fR\adetails2\x81\x02\n" +
	"\fControlPlane\x12E\n" +
	"\fRegisterPeer\x12\x1a.waemu.rpc.v1.PeerMetadata\x1a\x19.waemu.rpc.v1.RegisterAck\x12P\n" +
	"\tHeartbeat\x12\x1e.waemu.rpc.v1.HeartbeatRequest\x1a\x1f.waemu.rpc.v1.HeartbeatResponse(\x010\x01\x12X\n" +
	"\rUpdateMethods\x12\".waemu.rpc.v1.UpdateMethodsRequest\x1a#.waemu.rpc.v1.UpdateMethodsResponse2\xa1\x01\n" +
	"\vInvokePlane\x12C\n" +
	"\x06Invoke\x12\x1b.waemu.rpc.v1.InvokeRequest\x1a\x1c.waemu.rpc.v1.InvokeResponse\x12M\n" +
	"\fInvokeStream\x12\x1b.waemu.rpc.v1.InvokeRequest\x1a\x1c.waemu.rpc.v1.InvokeResponse(\x010\x01B/Z-github.com/grpc-mesh/grpc-mesh-server/pkg/rpcb\x06proto3"

var (
	file_waemu_proto_rawDescOnce sync.Once
	file_waemu_proto_rawDescData []byte
)

func file_waemu_proto_rawDescGZIP() []byte {
	file_waemu_proto_rawDescOnce.Do(func() {
		file_waemu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_waemu_proto_rawDesc), len(file_waemu_proto_rawDesc)))
	})
	return file_waemu_proto_rawDescData
}

var file_waemu_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_waemu_proto_goTypes = []any{
	(*PeerMetadata)(nil),          // 0: waemu.rpc.v1.PeerMetadata
	(*RegisterAck)(nil),           // 1: waemu.rpc.v1.RegisterAck
	(*HeartbeatRequest)(nil),      // 2: waemu.rpc.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 3: waemu.rpc.v1.HeartbeatResponse
	(*MethodDescriptor)(nil),      // 4: waemu.rpc.v1.MethodDescriptor
	(*UpdateMethodsRequest)(nil),  // 5: waemu.rpc.v1.UpdateMethodsRequest
	(*UpdateMethodsResponse)(nil), // 6: waemu.rpc.v1.UpdateMethodsResponse
	(*InvokeRequest)(nil),         // 7: waemu.rpc.v1.InvokeRequest
	(*InvokeResponse)(nil),        // 8: waemu.rpc.v1.InvokeResponse
	(*ErrorDetail)(nil),           // 9: waemu.rpc.v1.ErrorDetail
	nil,                           // 10: waemu.rpc.v1.PeerMetadata.AttributesEntry
	nil,                           // 11: waemu.rpc.v1.MethodDescriptor.ExtraEntry
}
var file_waemu_proto_depIdxs = []int32{
	10, // 0: waemu.rpc.v1.PeerMetadata.attributes:type_name -> waemu.rpc.v1.PeerMetadata.AttributesEntry
	0,  // 1: waemu.rpc.v1.HeartbeatRequest.meta:type_name -> waemu.rpc.v1.PeerMetadata
	11, // 2: waemu.rpc.v1.MethodDescriptor.extra:type_name -> waemu.rpc.v1.MethodDescriptor.ExtraEntry
	4,  // 3: waemu.rpc.v1.UpdateMethodsRequest.methods:type_name -> waemu.rpc.v1.MethodDescriptor
	9,  // 4: waemu.rpc.v1.InvokeResponse.error:type_name -> waemu.rpc.v1.ErrorDetail
	0,  // 5: waemu.rpc.v1.ControlPlane.RegisterPeer:input_type -> waemu.rpc.v1.PeerMetadata
	2,  // 6: waemu.rpc.v1.ControlPlane.Heartbeat:input_type -> waemu.rpc.v1.HeartbeatRequest
	5,  // 7: waemu.rpc.v1.ControlPlane.UpdateMethods:input_type -> waemu.rpc.v1.UpdateMethodsRequest
	7,  // 8: waemu.rpc.v1.InvokePlane.Invoke:input_type -> waemu.rpc.v1.InvokeRequest
	7,  // 9: waemu.rpc.v1.InvokePlane.InvokeStream:input_type -> waemu.rpc.v1.InvokeRequest
	1,  // 10: waemu.rpc.v1.ControlPlane.RegisterPeer:output_type -> waemu.rpc.v1.RegisterAck
	3,  // 11: waemu.rpc.v1.ControlPlane.Heartbeat:output_type -> waemu.rpc.v1.HeartbeatResponse
	6,  // 12: waemu.rpc.v1.ControlPlane.UpdateMethods:output_type -> waemu.rpc.v1.UpdateMethodsResponse
	8,  // 13: waemu.rpc.v1.InvokePlane.Invoke:output_type -> waemu.rpc.v1.InvokeResponse
	8,  // 14: waemu.rpc.v1.InvokePlane.InvokeStream:output_type -> waemu.rpc.v1.InvokeResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_waemu_proto_init() }
func file_waemu_proto_init() {
	if File_waemu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_waemu_proto_rawDesc), len(file_waemu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_waemu_proto_goTypes,
		DependencyIndexes: file_waemu_proto_depIdxs,
		MessageInfos:      file_waemu_proto_msgTypes,
	}.Build()
	File_waemu_proto = out.File
	file_waemu_proto_goTypes = nil
	file_waemu_proto_depIdxs = nil
}
